---
- name: Ansible Group and Host Varibles
  hosts: localhost

  tasks:
    - name: create router configuration files
      template:
        src=~/Desktop/python-Network/Chapter5/Includes/nxos.j2
        dest=~/Desktop/python-Network/Chapter5/Includes/{{ item.key }}.conf
      with_dict: "{{ nexus_devices }}"
      register: output

    - include: show_output.yml