---
- name: Your First Custom Module
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Show Version
      action: custom_module_1 host="192.168.17.22" username="cisco" password="cisco"
      register: output

    - debug:
        var: output