---
- name: IOS Command Output
  hosts: "ios-devices"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: show hostname
      ios_command:
        commands:
            - show run | i hostname

      register: output

    - name: config example
      when: '"iosv-2" in "{{ output.stdout }}"'
      ios_config:
        lines:
          - logging buffered 30000