---
- name: EOS Command Output
  hosts: "arista"
  gather_facts: False
  connection: local

  tasks:
    - name: "sh int ethernet 2 | json"
      eos_command:
        commands:
            - "show interface ethernet 2 | json"
        waitfor:
          - "result[0].interfaces.Ethernet2.interfaceStatus eq disabled"

      register: output
    - name: show output
      debug:
        msg: "Interface Disabled, Safe to Proceed"